language: python
python:
  - "2.7"
  - "3.5"
  
before_install:
    # required by Kivy
    - sudo apt-get install python-pip build-essential git python-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
  
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -v